import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, CircleDot, ClipboardList, KanbanSquare, Loader2, MessageSquare, MoreHorizontal, Plus, Search, StickyNote, Target, Trash2, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

import { PageHeader } from "@/components/dashboard/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAdminAccess } from "@/hooks/use-admin-access";

export const Route = createFileRoute("/dashboard/projects")({
  head: () => ({ meta: [{ title: "Project Management - CloudMonkey Dashboard" }] }),
  component: ProjectsPage,
});

async function requestJson<T = any>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, init);
  const data = await response.json().catch(() => null);
  if (!response.ok) throw new Error(data?.error || "Request failed");
  return data;
}

const columns = [
  ["backlog", "Backlog"], ["todo", "To do"], ["in_progress", "In progress"], ["blocked", "Blocked"], ["review", "Review"], ["done", "Done"],
] as const;

const statusTone: Record<string, string> = {
  planned: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200",
  active: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300",
  on_hold: "bg-amber-100 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300",
  completed: "bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-300",
  cancelled: "bg-red-100 text-red-700 dark:bg-red-950/50 dark:text-red-300",
};

const taskTone: Record<string, string> = {
  backlog: "bg-slate-400", todo: "bg-violet-500", in_progress: "bg-blue-500", blocked: "bg-red-500", review: "bg-amber-500", done: "bg-emerald-500",
};

function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function progressFor(tasks: any[]) { return tasks.length ? Math.round((tasks.filter((task) => task.status === "done").length / tasks.length) * 100) : 0; }

function ProjectsPage() {
  const { authReady, isAdmin } = useAdminAccess();
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState("");
  const [view, setView] = useState<"kanban" | "list">("kanban");
  const [showTaskForm, setShowTaskForm] = useState(false);
  const [comment, setComment] = useState("");
  const [note, setNote] = useState("");
  const [projectSearch, setProjectSearch] = useState("");

  const projects = useQuery({ queryKey: ["admin", "projects"], queryFn: () => requestJson<any[]>("/api/admin/projects"), enabled: authReady && isAdmin });
  const selected = selectedId || projects.data?.[0]?.id || "";
  const detail = useQuery({ queryKey: ["admin", "projects", selected], queryFn: () => requestJson<any>(`/api/admin/projects/${selected}`), enabled: authReady && isAdmin && !!selected });
  const users = useQuery({ queryKey: ["admin", "users", "project-members"], queryFn: () => requestJson<any[]>("/api/admin/users"), enabled: authReady && isAdmin });
  const project = detail.data?.project;
  const tasks = detail.data?.tasks || [];
  const admins = (users.data || []).filter((user: any) => ["admin", "owner", "support"].includes(user.role));
  const visibleProjects = (projects.data || []).filter((item: any) => `${item.name} ${item.serviceName} ${item.customer?.name || ""} ${item.customer?.email || ""}`.toLowerCase().includes(projectSearch.toLowerCase()));
  const progress = progressFor(tasks);

  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ["admin", "projects"] }), queryClient.invalidateQueries({ queryKey: ["admin", "projects", selected] })]);
  const updateProject = useMutation({ mutationFn: (body: any) => requestJson(`/api/admin/projects/${selected}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), onSuccess: refresh, onError: (error: Error) => toast.error(error.message) });
  const updateTask = useMutation({ mutationFn: ({ taskId, body }: any) => requestJson(`/api/admin/projects/${selected}/tasks/${taskId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), onSuccess: refresh, onError: (error: Error) => toast.error(error.message) });
  const addTask = useMutation({ mutationFn: (body: any) => requestJson(`/api/admin/projects/${selected}/tasks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), onSuccess: async () => { setShowTaskForm(false); toast.success("Task added"); await refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const addComment = useMutation({ mutationFn: () => requestJson(`/api/admin/projects/${selected}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: comment, isInternal: false }) }), onSuccess: async () => { setComment(""); toast.success("Customer notified"); await refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const addNote = useMutation({ mutationFn: () => requestJson(`/api/admin/projects/${selected}/notes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: note }) }), onSuccess: async () => { setNote(""); toast.success("Private note saved"); await refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const deleteNote = useMutation({ mutationFn: (noteId: string) => requestJson(`/api/admin/projects/${selected}/notes/${noteId}`, { method: "DELETE" }), onSuccess: refresh, onError: (error: Error) => toast.error(error.message) });

  const counts = useMemo(() => columns.map(([status]) => [status, tasks.filter((task: any) => task.status === status).length] as const), [tasks]);
  if (!authReady || !isAdmin) return <div className="p-8 text-center">Checking permissions...</div>;

  return <div className="space-y-6">
    <PageHeader eyebrow="Administration / Workspace" title="Projects" subtitle="Plan, assign and deliver every CloudMonkey setup and development engagement from one workspace." actions={<div className="flex items-center gap-1 rounded-xl border bg-muted/40 p-1"><Button variant={view === "kanban" ? "default" : "ghost"} size="sm" className="rounded-lg" onClick={() => setView("kanban")}><KanbanSquare className="h-4 w-4" />Board</Button><Button variant={view === "list" ? "default" : "ghost"} size="sm" className="rounded-lg" onClick={() => setView("list")}><ClipboardList className="h-4 w-4" />List</Button></div>} />
    <div className="grid gap-4 md:grid-cols-4"><Metric label="Projects" value={projects.data?.length || 0} icon={Target} /><Metric label="Active" value={projects.data?.filter((item: any) => item.status === "active").length || 0} icon={CircleDot} /><Metric label="Open tasks" value={tasks.filter((item: any) => item.status !== "done").length} icon={ClipboardList} /><Metric label="Done tasks" value={tasks.filter((item: any) => item.status === "done").length} icon={CheckCircle2} /></div>
    <div className="grid gap-6 xl:grid-cols-[280px_1fr]">
      <Card className="overflow-hidden border-0 shadow-sm ring-1 ring-border/60"><CardHeader className="space-y-3 border-b bg-muted/20 pb-4"><div className="flex items-center justify-between"><CardTitle className="text-sm font-semibold">Projects</CardTitle><Badge variant="secondary" className="rounded-md">{projects.data?.length || 0}</Badge></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={projectSearch} onChange={(event) => setProjectSearch(event.target.value)} placeholder="Search projects..." className="h-9 rounded-lg pl-9 text-sm" /></div></CardHeader><CardContent className="space-y-1 p-2">{projects.isLoading ? <Loader2 className="m-4 h-5 w-5 animate-spin" /> : visibleProjects.length ? visibleProjects.map((item: any) => <button key={item.id} type="button" onClick={() => setSelectedId(item.id)} className={`group w-full rounded-lg border-l-2 p-3 text-left transition ${selected === item.id ? "border-l-[var(--ai)] bg-[var(--ai)]/8" : "border-l-transparent hover:bg-muted/50"}`}><div className="flex items-start justify-between gap-2"><div className="truncate text-sm font-semibold">{item.name}</div><MoreHorizontal className="h-4 w-4 shrink-0 text-muted-foreground opacity-0 transition group-hover:opacity-100" /></div><div className="mt-1 truncate text-xs text-muted-foreground">{item.customer?.name || item.customer?.email}</div><div className="mt-2 flex items-center justify-between gap-2"><span className={`rounded-md px-2 py-0.5 text-[10px] font-semibold capitalize ${statusTone[item.status] || statusTone.planned}`}>{label(item.status)}</span><span className="truncate text-[10px] text-muted-foreground">{item.serviceName}</span></div></button>) : <p className="p-3 text-sm text-muted-foreground">No matching projects.</p>}</CardContent></Card>
      <div className="space-y-6">{!project ? <Card><CardContent className="p-10 text-center text-muted-foreground">Select a project to manage delivery.</CardContent></Card> : <>
        <Card className="overflow-hidden border-0 shadow-sm ring-1 ring-border/60"><CardContent className="space-y-5 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold tracking-tight">{project.name}</h2><span className={`rounded-md px-2.5 py-1 text-xs font-semibold ${statusTone[project.status] || statusTone.planned}`}>{label(project.status)}</span><span className="rounded-md bg-muted px-2.5 py-1 text-xs text-muted-foreground">{label(project.template)}</span></div><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><UserRound className="h-3.5 w-3.5" />{project.customer?.name || project.userId} <span>·</span> {project.serviceName}</p><p className="mt-3 max-w-3xl text-sm leading-6">{project.description || "Implementation project created from a signed CloudMonkey service."}</p></div><div className="flex items-center gap-2"><select className="h-9 rounded-lg border bg-background px-3 text-sm" value={project.status} onChange={(event) => updateProject.mutate({ status: event.target.value })}>{["planned", "active", "on_hold", "completed", "cancelled"].map((status) => <option key={status} value={status}>{label(status)}</option>)}</select><Button className="rounded-lg" onClick={() => setShowTaskForm((value) => !value)}><Plus className="h-4 w-4" />New task</Button></div></div><div className="flex flex-wrap items-center gap-5 border-t pt-4"><div className="min-w-[180px] flex-1"><div className="mb-2 flex justify-between text-xs"><span className="font-medium">Project progress</span><span className="font-semibold">{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[var(--ai)] transition-all" style={{ width: `${progress}%` }} /></div></div><div className="flex flex-wrap gap-3">{counts.map(([status, count]) => <span key={status} className="flex items-center gap-1.5 text-xs text-muted-foreground"><i className={`h-2 w-2 rounded-full ${taskTone[status]}`} />{label(status)} <strong className="text-foreground">{count}</strong></span>)}</div></div></CardContent></Card>
        {showTaskForm && <TaskForm milestones={detail.data?.milestones || []} admins={admins} onCancel={() => setShowTaskForm(false)} onSubmit={(body) => addTask.mutate(body)} pending={addTask.isPending} />}
        {view === "kanban" ? <div className="grid gap-3 overflow-x-auto pb-2 lg:grid-cols-6">{columns.map(([status, columnLabel]) => <div key={status} className="min-w-[190px] rounded-xl border bg-muted/20 p-2.5"><div className="mb-3 flex items-center justify-between px-1 text-[11px] font-bold uppercase tracking-wide"><span className="flex items-center gap-2"><i className={`h-2.5 w-2.5 rounded-full ${taskTone[status]}`} />{columnLabel}</span><span className="rounded-md bg-background px-2 py-0.5 text-xs text-muted-foreground">{tasks.filter((task: any) => task.status === status).length}</span></div><div className="space-y-2">{tasks.filter((task: any) => task.status === status).map((task: any) => <TaskCard key={task.id} task={task} admins={admins} onChange={(body) => updateTask.mutate({ taskId: task.id, body })} />)}</div></div>)}</div> : <Card className="overflow-hidden border-0 shadow-sm ring-1 ring-border/60"><CardContent className="divide-y p-0">{tasks.map((task: any) => <div key={task.id} className="grid gap-3 p-4 transition hover:bg-muted/20 md:grid-cols-[1fr_160px_180px]"><div><div className="flex items-center gap-2 font-semibold"><i className={`h-2 w-2 rounded-full ${taskTone[task.status]}`} />{task.title}</div><div className="mt-1 text-sm text-muted-foreground">{task.description || "No task description"}</div></div><select className="h-9 rounded-lg border bg-background px-2 text-sm" value={task.status} onChange={(event) => updateTask.mutate({ taskId: task.id, body: { status: event.target.value } })}>{columns.map(([value, columnLabel]) => <option key={value} value={value}>{columnLabel}</option>)}</select><select className="h-9 rounded-lg border bg-background px-2 text-sm" value={task.assignedToUserId || ""} onChange={(event) => updateTask.mutate({ taskId: task.id, body: { assignedToUserId: event.target.value || null } })}><option value="">Unassigned</option>{admins.map((admin: any) => <option key={admin.id} value={admin.id}>{admin.name || admin.email}</option>)}</select></div>)}</CardContent></Card>}
        <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Target className="h-4 w-4" />Milestones</CardTitle></CardHeader><CardContent className="space-y-3">{(detail.data?.milestones || []).map((milestone: any) => <div key={milestone.id} className="rounded-lg border p-3"><div className="font-semibold">{milestone.name}</div><div className="text-xs capitalize text-muted-foreground">{milestone.status.replaceAll("_", " ")}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CheckCircle2 className="h-4 w-4" />Deliverables</CardTitle></CardHeader><CardContent className="space-y-3">{(detail.data?.deliverables || []).length ? detail.data.deliverables.map((item: any) => <div key={item.id} className="rounded-lg border p-3"><div className="font-semibold">{item.name}</div><div className="text-xs capitalize text-muted-foreground">{item.status.replaceAll("_", " ")}</div></div>) : <p className="text-sm text-muted-foreground">Add deliverables from the project API as scope is confirmed.</p>}</CardContent></Card></div>
        <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><StickyNote className="h-4 w-4" />Private project notes</CardTitle><p className="text-sm text-muted-foreground">Internal only — use for domain links, credentials handover reminders, dependencies and delivery context. Customers cannot see these notes or receive notifications.</p></CardHeader><CardContent className="space-y-4"><Textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="e.g. Link ketiwe.co.za after customer confirms the domain..." rows={3} /><div className="flex justify-end"><Button className="rounded-xl" disabled={!note.trim() || addNote.isPending} onClick={() => addNote.mutate()}><StickyNote className="h-4 w-4" />Save private note</Button></div>{(detail.data?.notes || []).length ? detail.data.notes.slice(0, 12).map((item: any) => <div key={item.id} className="flex items-start justify-between gap-3 border-t pt-3 text-sm"><div><div className="font-semibold">{item.author?.name || "CloudMonkey"} <span className="font-normal text-muted-foreground">· {new Date(item.createdAt).toLocaleString()}</span></div><p className="whitespace-pre-wrap text-muted-foreground">{item.body}</p></div><Button variant="ghost" size="icon" aria-label="Delete private note" onClick={() => deleteNote.mutate(item.id)} disabled={deleteNote.isPending}><Trash2 className="h-4 w-4 text-muted-foreground" /></Button></div>) : <p className="text-sm text-muted-foreground">No private notes yet.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><MessageSquare className="h-4 w-4" />Customer communication</CardTitle></CardHeader><CardContent className="space-y-4"><Textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Write an update for the customer..." rows={3} /><div className="flex justify-end"><Button className="rounded-xl" disabled={!comment.trim() || addComment.isPending} onClick={() => addComment.mutate()}><MessageSquare className="h-4 w-4" />Post update and notify customer</Button></div>{(detail.data?.comments || []).slice(0, 6).map((item: any) => <div key={item.id} className="border-t pt-3 text-sm"><div className="font-semibold">{item.author?.name || "CloudMonkey"}</div><p className="text-muted-foreground">{item.body}</p></div>)}</CardContent></Card></div>
      </>}</div>
    </div>
  </div>;
}

function TaskForm({ milestones, admins, onCancel, onSubmit, pending }: any) { const [form, setForm] = useState({ title: "", description: "", milestoneId: "", assignedToUserId: "", priority: "medium" }); return <Card><CardHeader><CardTitle className="text-base">New project task</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="space-y-2 md:col-span-2"><Label>Task</Label><Input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Configure payment provider" /></div><div className="space-y-2 md:col-span-2"><Label>Description</Label><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div><div className="space-y-2"><Label>Milestone</Label><select className="h-10 w-full rounded-lg border bg-background px-3 text-sm" value={form.milestoneId} onChange={(event) => setForm({ ...form, milestoneId: event.target.value })}><option value="">No milestone</option>{milestones.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="space-y-2"><Label>Assigned admin</Label><select className="h-10 w-full rounded-lg border bg-background px-3 text-sm" value={form.assignedToUserId} onChange={(event) => setForm({ ...form, assignedToUserId: event.target.value })}><option value="">Unassigned</option>{admins.map((item: any) => <option key={item.id} value={item.id}>{item.name || item.email}</option>)}</select></div><div className="flex justify-end gap-2 md:col-span-2"><Button variant="outline" onClick={onCancel}>Cancel</Button><Button disabled={!form.title.trim() || pending} onClick={() => onSubmit(form)}>{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Create task</Button></div></CardContent></Card>; }
function TaskCard({ task, admins, onChange }: any) { return <div className="group rounded-lg border bg-card p-3 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-2"><div className="text-sm font-semibold leading-5">{task.title}</div><MoreHorizontal className="h-4 w-4 shrink-0 text-muted-foreground opacity-0 transition group-hover:opacity-100" /></div>{task.description ? <p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{task.description}</p> : null}<div className="mt-3 flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-[11px] text-muted-foreground"><UserRound className="h-3 w-3" />{task.assignee?.name || "Unassigned"}</span><span className="rounded px-1.5 py-0.5 text-[10px] font-semibold capitalize text-muted-foreground">{task.priority || "medium"}</span></div><div className="mt-3 space-y-2 border-t pt-2"><select aria-label={`Change status for ${task.title}`} className="h-8 w-full rounded-md border bg-background px-2 text-xs" value={task.status} onChange={(event) => onChange({ status: event.target.value })}>{columns.map(([value, columnLabel]) => <option key={value} value={value}>{columnLabel}</option>)}</select><select aria-label={`Assign ${task.title}`} className="h-8 w-full rounded-md border bg-background px-2 text-xs" value={task.assignedToUserId || ""} onChange={(event) => onChange({ assignedToUserId: event.target.value || null })}><option value="">Unassigned</option>{admins.map((item: any) => <option key={item.id} value={item.id}>{item.name || item.email}</option>)}</select></div></div>; }
function Metric({ label, value, icon: Icon }: any) { return <Card><CardContent className="p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground"><Icon className="h-4 w-4" />{label}</div><div className="mt-2 text-2xl font-bold">{value}</div></CardContent></Card>; }
