/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as WebsiteApprovalTokenRouteImport } from './routes/website-approval/$token'
import { Route as DashboardWebsitesRouteImport } from './routes/dashboard/websites'
import { Route as DashboardWebsiteWizardRouteImport } from './routes/dashboard/website-wizard'
import { Route as DashboardWebsiteProjectsRouteImport } from './routes/dashboard/website-projects'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardIntelligenceWizardRouteImport } from './routes/dashboard/intelligence-wizard'
import { Route as DashboardIntelligenceRouteImport } from './routes/dashboard/intelligence'
import { Route as DashboardHostingRouteImport } from './routes/dashboard/hosting'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard/domains'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardCrmRouteImport } from './routes/dashboard/crm'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAiWizardRouteImport } from './routes/dashboard/ai-wizard'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardAffiliatesRouteImport } from './routes/dashboard/affiliates'
import { Route as DashboardAffiliateAdminRouteImport } from './routes/dashboard/affiliate-admin'
import { Route as DashboardAdministrationRouteImport } from './routes/dashboard/administration'
import { Route as DashboardActivityLogsRouteImport } from './routes/dashboard/activity-logs'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSsoErrorRouteImport } from './routes/auth/sso-error'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth/sso-callback'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLinkAccountRouteImport } from './routes/auth/link-account'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardWebsitesWebsiteIdRouteImport } from './routes/dashboard/websites/$websiteId'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId'
import { Route as DashboardSupportTicketIdRouteImport } from './routes/dashboard/support/$ticketId'
import { Route as DashboardDomainsNewRouteImport } from './routes/dashboard/domains/new'
import { Route as DashboardBillingInvoicesInvoiceIdRouteImport } from './routes/dashboard/billing/invoices/$invoiceId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteApprovalTokenRoute = WebsiteApprovalTokenRouteImport.update({
  id: '/website-approval/$token',
  path: '/website-approval/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebsitesRoute = DashboardWebsitesRouteImport.update({
  id: '/dashboard/websites',
  path: '/dashboard/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebsiteWizardRoute = DashboardWebsiteWizardRouteImport.update({
  id: '/dashboard/website-wizard',
  path: '/dashboard/website-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebsiteProjectsRoute =
  DashboardWebsiteProjectsRouteImport.update({
    id: '/dashboard/website-projects',
    path: '/dashboard/website-projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/dashboard/roles',
  path: '/dashboard/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/dashboard/products',
  path: '/dashboard/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIntelligenceWizardRoute =
  DashboardIntelligenceWizardRouteImport.update({
    id: '/dashboard/intelligence-wizard',
    path: '/dashboard/intelligence-wizard',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardIntelligenceRoute = DashboardIntelligenceRouteImport.update({
  id: '/dashboard/intelligence',
  path: '/dashboard/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHostingRoute = DashboardHostingRouteImport.update({
  id: '/dashboard/hosting',
  path: '/dashboard/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/dashboard/domains',
  path: '/dashboard/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/dashboard/customers',
  path: '/dashboard/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/dashboard/crm',
  path: '/dashboard/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiWizardRoute = DashboardAiWizardRouteImport.update({
  id: '/dashboard/ai-wizard',
  path: '/dashboard/ai-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/dashboard/agents',
  path: '/dashboard/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAffiliatesRoute = DashboardAffiliatesRouteImport.update({
  id: '/dashboard/affiliates',
  path: '/dashboard/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAffiliateAdminRoute = DashboardAffiliateAdminRouteImport.update({
  id: '/dashboard/affiliate-admin',
  path: '/dashboard/affiliate-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdministrationRoute = DashboardAdministrationRouteImport.update({
  id: '/dashboard/administration',
  path: '/dashboard/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardActivityLogsRoute = DashboardActivityLogsRouteImport.update({
  id: '/dashboard/activity-logs',
  path: '/dashboard/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoErrorRoute = AuthSsoErrorRouteImport.update({
  id: '/auth/sso-error',
  path: '/auth/sso-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/auth/sso-callback',
  path: '/auth/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkAccountRoute = AuthLinkAccountRouteImport.update({
  id: '/auth/link-account',
  path: '/auth/link-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebsitesWebsiteIdRoute =
  DashboardWebsitesWebsiteIdRouteImport.update({
    id: '/$websiteId',
    path: '/$websiteId',
    getParentRoute: () => DashboardWebsitesRoute,
  } as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const DashboardSupportTicketIdRoute =
  DashboardSupportTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => DashboardSupportRoute,
  } as any)
const DashboardDomainsNewRoute = DashboardDomainsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardDomainsRoute,
} as any)
const DashboardBillingInvoicesInvoiceIdRoute =
  DashboardBillingInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => DashboardBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/ai': typeof AiRoute
  '/ai-agents': typeof AiAgentsRoute
  '/business': typeof BusinessRoute
  '/cloud': typeof CloudRoute
  '/domains': typeof DomainsRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/link-account': typeof AuthLinkAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
  '/auth/sso-error': typeof AuthSsoErrorRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard': typeof DashboardLayoutRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/administration': typeof DashboardAdministrationRoute
  '/dashboard/affiliate-admin': typeof DashboardAffiliateAdminRoute
  '/dashboard/affiliates': typeof DashboardAffiliatesRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/ai-wizard': typeof DashboardAiWizardRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/domains': typeof DashboardDomainsRouteWithChildren
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/intelligence-wizard': typeof DashboardIntelligenceWizardRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/dashboard/website-projects': typeof DashboardWebsiteProjectsRoute
  '/dashboard/website-wizard': typeof DashboardWebsiteWizardRoute
  '/dashboard/websites': typeof DashboardWebsitesRouteWithChildren
  '/website-approval/$token': typeof WebsiteApprovalTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/domains/new': typeof DashboardDomainsNewRoute
  '/dashboard/support/$ticketId': typeof DashboardSupportTicketIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/websites/$websiteId': typeof DashboardWebsitesWebsiteIdRoute
  '/dashboard/billing/invoices/$invoiceId': typeof DashboardBillingInvoicesInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/ai': typeof AiRoute
  '/ai-agents': typeof AiAgentsRoute
  '/business': typeof BusinessRoute
  '/cloud': typeof CloudRoute
  '/domains': typeof DomainsRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/link-account': typeof AuthLinkAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
  '/auth/sso-error': typeof AuthSsoErrorRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/administration': typeof DashboardAdministrationRoute
  '/dashboard/affiliate-admin': typeof DashboardAffiliateAdminRoute
  '/dashboard/affiliates': typeof DashboardAffiliatesRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/ai-wizard': typeof DashboardAiWizardRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/domains': typeof DashboardDomainsRouteWithChildren
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/intelligence-wizard': typeof DashboardIntelligenceWizardRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/dashboard/website-projects': typeof DashboardWebsiteProjectsRoute
  '/dashboard/website-wizard': typeof DashboardWebsiteWizardRoute
  '/dashboard/websites': typeof DashboardWebsitesRouteWithChildren
  '/website-approval/$token': typeof WebsiteApprovalTokenRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/domains/new': typeof DashboardDomainsNewRoute
  '/dashboard/support/$ticketId': typeof DashboardSupportTicketIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/websites/$websiteId': typeof DashboardWebsitesWebsiteIdRoute
  '/dashboard/billing/invoices/$invoiceId': typeof DashboardBillingInvoicesInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/ai': typeof AiRoute
  '/ai-agents': typeof AiAgentsRoute
  '/business': typeof BusinessRoute
  '/cloud': typeof CloudRoute
  '/domains': typeof DomainsRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/link-account': typeof AuthLinkAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
  '/auth/sso-error': typeof AuthSsoErrorRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/_layout': typeof DashboardLayoutRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/administration': typeof DashboardAdministrationRoute
  '/dashboard/affiliate-admin': typeof DashboardAffiliateAdminRoute
  '/dashboard/affiliates': typeof DashboardAffiliatesRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/ai-wizard': typeof DashboardAiWizardRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/domains': typeof DashboardDomainsRouteWithChildren
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/intelligence-wizard': typeof DashboardIntelligenceWizardRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/dashboard/website-projects': typeof DashboardWebsiteProjectsRoute
  '/dashboard/website-wizard': typeof DashboardWebsiteWizardRoute
  '/dashboard/websites': typeof DashboardWebsitesRouteWithChildren
  '/website-approval/$token': typeof WebsiteApprovalTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/domains/new': typeof DashboardDomainsNewRoute
  '/dashboard/support/$ticketId': typeof DashboardSupportTicketIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/websites/$websiteId': typeof DashboardWebsitesWebsiteIdRoute
  '/dashboard/billing/invoices/$invoiceId': typeof DashboardBillingInvoicesInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliates'
    | '/ai'
    | '/ai-agents'
    | '/business'
    | '/cloud'
    | '/domains'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso-callback'
    | '/auth/sso-error'
    | '/auth/verify-email'
    | '/dashboard'
    | '/dashboard/activity-logs'
    | '/dashboard/administration'
    | '/dashboard/affiliate-admin'
    | '/dashboard/affiliates'
    | '/dashboard/agents'
    | '/dashboard/ai-wizard'
    | '/dashboard/billing'
    | '/dashboard/crm'
    | '/dashboard/customers'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/intelligence'
    | '/dashboard/intelligence-wizard'
    | '/dashboard/products'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/users'
    | '/dashboard/website-projects'
    | '/dashboard/website-wizard'
    | '/dashboard/websites'
    | '/website-approval/$token'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/domains/new'
    | '/dashboard/support/$ticketId'
    | '/dashboard/users/$userId'
    | '/dashboard/websites/$websiteId'
    | '/dashboard/billing/invoices/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliates'
    | '/ai'
    | '/ai-agents'
    | '/business'
    | '/cloud'
    | '/domains'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso-callback'
    | '/auth/sso-error'
    | '/auth/verify-email'
    | '/dashboard'
    | '/dashboard/activity-logs'
    | '/dashboard/administration'
    | '/dashboard/affiliate-admin'
    | '/dashboard/affiliates'
    | '/dashboard/agents'
    | '/dashboard/ai-wizard'
    | '/dashboard/billing'
    | '/dashboard/crm'
    | '/dashboard/customers'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/intelligence'
    | '/dashboard/intelligence-wizard'
    | '/dashboard/products'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/users'
    | '/dashboard/website-projects'
    | '/dashboard/website-wizard'
    | '/dashboard/websites'
    | '/website-approval/$token'
    | '/auth'
    | '/dashboard/domains/new'
    | '/dashboard/support/$ticketId'
    | '/dashboard/users/$userId'
    | '/dashboard/websites/$websiteId'
    | '/dashboard/billing/invoices/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/affiliates'
    | '/ai'
    | '/ai-agents'
    | '/business'
    | '/cloud'
    | '/domains'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso-callback'
    | '/auth/sso-error'
    | '/auth/verify-email'
    | '/dashboard/_layout'
    | '/dashboard/activity-logs'
    | '/dashboard/administration'
    | '/dashboard/affiliate-admin'
    | '/dashboard/affiliates'
    | '/dashboard/agents'
    | '/dashboard/ai-wizard'
    | '/dashboard/billing'
    | '/dashboard/crm'
    | '/dashboard/customers'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/intelligence'
    | '/dashboard/intelligence-wizard'
    | '/dashboard/products'
    | '/dashboard/reports'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/users'
    | '/dashboard/website-projects'
    | '/dashboard/website-wizard'
    | '/dashboard/websites'
    | '/website-approval/$token'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/domains/new'
    | '/dashboard/support/$ticketId'
    | '/dashboard/users/$userId'
    | '/dashboard/websites/$websiteId'
    | '/dashboard/billing/invoices/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AiRoute: typeof AiRoute
  AiAgentsRoute: typeof AiAgentsRoute
  BusinessRoute: typeof BusinessRoute
  CloudRoute: typeof CloudRoute
  DomainsRoute: typeof DomainsRoute
  PricingRoute: typeof PricingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLinkAccountRoute: typeof AuthLinkAccountRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
  AuthSsoErrorRoute: typeof AuthSsoErrorRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  DashboardActivityLogsRoute: typeof DashboardActivityLogsRoute
  DashboardAdministrationRoute: typeof DashboardAdministrationRoute
  DashboardAffiliateAdminRoute: typeof DashboardAffiliateAdminRoute
  DashboardAffiliatesRoute: typeof DashboardAffiliatesRoute
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAiWizardRoute: typeof DashboardAiWizardRoute
  DashboardBillingRoute: typeof DashboardBillingRouteWithChildren
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDomainsRoute: typeof DashboardDomainsRouteWithChildren
  DashboardHostingRoute: typeof DashboardHostingRoute
  DashboardIntelligenceRoute: typeof DashboardIntelligenceRoute
  DashboardIntelligenceWizardRoute: typeof DashboardIntelligenceWizardRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRouteWithChildren
  DashboardWebsiteProjectsRoute: typeof DashboardWebsiteProjectsRoute
  DashboardWebsiteWizardRoute: typeof DashboardWebsiteWizardRoute
  DashboardWebsitesRoute: typeof DashboardWebsitesRouteWithChildren
  WebsiteApprovalTokenRoute: typeof WebsiteApprovalTokenRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-approval/$token': {
      id: '/website-approval/$token'
      path: '/website-approval/$token'
      fullPath: '/website-approval/$token'
      preLoaderRoute: typeof WebsiteApprovalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/websites': {
      id: '/dashboard/websites'
      path: '/dashboard/websites'
      fullPath: '/dashboard/websites'
      preLoaderRoute: typeof DashboardWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/website-wizard': {
      id: '/dashboard/website-wizard'
      path: '/dashboard/website-wizard'
      fullPath: '/dashboard/website-wizard'
      preLoaderRoute: typeof DashboardWebsiteWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/website-projects': {
      id: '/dashboard/website-projects'
      path: '/dashboard/website-projects'
      fullPath: '/dashboard/website-projects'
      preLoaderRoute: typeof DashboardWebsiteProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/dashboard/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/dashboard/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/intelligence-wizard': {
      id: '/dashboard/intelligence-wizard'
      path: '/dashboard/intelligence-wizard'
      fullPath: '/dashboard/intelligence-wizard'
      preLoaderRoute: typeof DashboardIntelligenceWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/intelligence': {
      id: '/dashboard/intelligence'
      path: '/dashboard/intelligence'
      fullPath: '/dashboard/intelligence'
      preLoaderRoute: typeof DashboardIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/hosting': {
      id: '/dashboard/hosting'
      path: '/dashboard/hosting'
      fullPath: '/dashboard/hosting'
      preLoaderRoute: typeof DashboardHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/dashboard/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/dashboard/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/crm': {
      id: '/dashboard/crm'
      path: '/dashboard/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-wizard': {
      id: '/dashboard/ai-wizard'
      path: '/dashboard/ai-wizard'
      fullPath: '/dashboard/ai-wizard'
      preLoaderRoute: typeof DashboardAiWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/affiliates': {
      id: '/dashboard/affiliates'
      path: '/dashboard/affiliates'
      fullPath: '/dashboard/affiliates'
      preLoaderRoute: typeof DashboardAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/affiliate-admin': {
      id: '/dashboard/affiliate-admin'
      path: '/dashboard/affiliate-admin'
      fullPath: '/dashboard/affiliate-admin'
      preLoaderRoute: typeof DashboardAffiliateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/administration': {
      id: '/dashboard/administration'
      path: '/dashboard/administration'
      fullPath: '/dashboard/administration'
      preLoaderRoute: typeof DashboardAdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/activity-logs': {
      id: '/dashboard/activity-logs'
      path: '/dashboard/activity-logs'
      fullPath: '/dashboard/activity-logs'
      preLoaderRoute: typeof DashboardActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-error': {
      id: '/auth/sso-error'
      path: '/auth/sso-error'
      fullPath: '/auth/sso-error'
      preLoaderRoute: typeof AuthSsoErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-callback': {
      id: '/auth/sso-callback'
      path: '/auth/sso-callback'
      fullPath: '/auth/sso-callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link-account': {
      id: '/auth/link-account'
      path: '/auth/link-account'
      fullPath: '/auth/link-account'
      preLoaderRoute: typeof AuthLinkAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/websites/$websiteId': {
      id: '/dashboard/websites/$websiteId'
      path: '/$websiteId'
      fullPath: '/dashboard/websites/$websiteId'
      preLoaderRoute: typeof DashboardWebsitesWebsiteIdRouteImport
      parentRoute: typeof DashboardWebsitesRoute
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/dashboard/support/$ticketId': {
      id: '/dashboard/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/dashboard/support/$ticketId'
      preLoaderRoute: typeof DashboardSupportTicketIdRouteImport
      parentRoute: typeof DashboardSupportRoute
    }
    '/dashboard/domains/new': {
      id: '/dashboard/domains/new'
      path: '/new'
      fullPath: '/dashboard/domains/new'
      preLoaderRoute: typeof DashboardDomainsNewRouteImport
      parentRoute: typeof DashboardDomainsRoute
    }
    '/dashboard/billing/invoices/$invoiceId': {
      id: '/dashboard/billing/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/dashboard/billing/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardBillingInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
  }
}

interface DashboardBillingRouteChildren {
  DashboardBillingInvoicesInvoiceIdRoute: typeof DashboardBillingInvoicesInvoiceIdRoute
}

const DashboardBillingRouteChildren: DashboardBillingRouteChildren = {
  DashboardBillingInvoicesInvoiceIdRoute:
    DashboardBillingInvoicesInvoiceIdRoute,
}

const DashboardBillingRouteWithChildren =
  DashboardBillingRoute._addFileChildren(DashboardBillingRouteChildren)

interface DashboardDomainsRouteChildren {
  DashboardDomainsNewRoute: typeof DashboardDomainsNewRoute
}

const DashboardDomainsRouteChildren: DashboardDomainsRouteChildren = {
  DashboardDomainsNewRoute: DashboardDomainsNewRoute,
}

const DashboardDomainsRouteWithChildren =
  DashboardDomainsRoute._addFileChildren(DashboardDomainsRouteChildren)

interface DashboardSupportRouteChildren {
  DashboardSupportTicketIdRoute: typeof DashboardSupportTicketIdRoute
}

const DashboardSupportRouteChildren: DashboardSupportRouteChildren = {
  DashboardSupportTicketIdRoute: DashboardSupportTicketIdRoute,
}

const DashboardSupportRouteWithChildren =
  DashboardSupportRoute._addFileChildren(DashboardSupportRouteChildren)

interface DashboardUsersRouteChildren {
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
}

const DashboardUsersRouteChildren: DashboardUsersRouteChildren = {
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
}

const DashboardUsersRouteWithChildren = DashboardUsersRoute._addFileChildren(
  DashboardUsersRouteChildren,
)

interface DashboardWebsitesRouteChildren {
  DashboardWebsitesWebsiteIdRoute: typeof DashboardWebsitesWebsiteIdRoute
}

const DashboardWebsitesRouteChildren: DashboardWebsitesRouteChildren = {
  DashboardWebsitesWebsiteIdRoute: DashboardWebsitesWebsiteIdRoute,
}

const DashboardWebsitesRouteWithChildren =
  DashboardWebsitesRoute._addFileChildren(DashboardWebsitesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliatesRoute: AffiliatesRoute,
  AiRoute: AiRoute,
  AiAgentsRoute: AiAgentsRoute,
  BusinessRoute: BusinessRoute,
  CloudRoute: CloudRoute,
  DomainsRoute: DomainsRoute,
  PricingRoute: PricingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLinkAccountRoute: AuthLinkAccountRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
  AuthSsoErrorRoute: AuthSsoErrorRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardActivityLogsRoute: DashboardActivityLogsRoute,
  DashboardAdministrationRoute: DashboardAdministrationRoute,
  DashboardAffiliateAdminRoute: DashboardAffiliateAdminRoute,
  DashboardAffiliatesRoute: DashboardAffiliatesRoute,
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardAiWizardRoute: DashboardAiWizardRoute,
  DashboardBillingRoute: DashboardBillingRouteWithChildren,
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDomainsRoute: DashboardDomainsRouteWithChildren,
  DashboardHostingRoute: DashboardHostingRoute,
  DashboardIntelligenceRoute: DashboardIntelligenceRoute,
  DashboardIntelligenceWizardRoute: DashboardIntelligenceWizardRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRouteWithChildren,
  DashboardWebsiteProjectsRoute: DashboardWebsiteProjectsRoute,
  DashboardWebsiteWizardRoute: DashboardWebsiteWizardRoute,
  DashboardWebsitesRoute: DashboardWebsitesRouteWithChildren,
  WebsiteApprovalTokenRoute: WebsiteApprovalTokenRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
